In [3]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from factor_analyzer import FactorAnalyzer
from factor_analyzer.factor_analyzer import calculate_kmo, calculate_bartlett_sphericity
import seaborn as sns
import matplotlib.pyplot as plt
from semopy import Model
import semopy


df2 = pd.read_excel('C:\\Users\\Girisha Jain\\MainData.xlsx')

In [4]:
df = df2.iloc[:,1:32]

In [5]:
df.columns

Index(['BB_ToU', 'BB_AcademicReputation', 'BB_ProgramOffered',
       'BB_CourseCurriculum', 'BB_CulturalExperience',
       'BB_Facilities_resources', 'BB_SafetyCampus', 'BB_DressCode',
       'BB_Infrastructure', 'BB_FacultyProfile', 'BB_Discipline',
       'BB_CareerOpportunities', 'BB_HS', 'SN_Family', 'SN_Friends',
       'SN_Seniors', 'SN_RelativesNeighbors', 'SN_Teachers',
       'SN_SameBehaviour', 'Selfesteem', 'PB_ScholarshipAvailability',
       'PB_UniversityTeamGuidance', 'PB_LanguageSpoken',
       'PB_AccomodationCostofLiving', 'PB_SafetyinCampus',
       'PB_UniversitylocatedCity', 'PB_CourseFee', 'PB_Ranking',
       'PB_ReputationBrand', 'PB_AvailabilityofCourse', 'PB_NearbytoHome'],
      dtype='object')

In [6]:
for col in df.columns:
    print(f"{col}: {df[col].unique()}")
    # Define the value mapping

BB_ToU: ['Very Important' 'Important' 'Very Unimportant' 'Unimportant' 'Neutral']
BB_AcademicReputation: ['Very Important' 'Very Unimportant' 'Important' 'Neutral' 'Unimportant']
BB_ProgramOffered: ['Very Important' 'Very Unimportant' 'Important' 'Neutral' 'Unimportant']
BB_CourseCurriculum: ['Very Important' 'Very Unimportant' 'Important' 'Neutral' 'Unimportant']
BB_CulturalExperience: ['Very Important' 'Very Unimportant' 'Neutral' 'Unimportant' 'Important']
BB_Facilities_resources: ['Very Important' 'Very Unimportant' 'Neutral' 'Important' 'Unimportant']
BB_SafetyCampus: ['Very Important' 'Very Unimportant' 'Important' 'Neutral' 'Unimportant']
BB_DressCode: ['Important' 'Very Unimportant' 'Very Important' 'Unimportant' 'Neutral']
BB_Infrastructure: ['Important' 'Very Unimportant' 'Neutral' 'Unimportant' 'Very Important']
BB_FacultyProfile: ['Very Important' 'Very Unimportant' 'Neutral' 'Important' 'Unimportant']
BB_Discipline: ['Very Important' 'Very Unimportant' 'Unimportant' 'Important' 'Neutral']
BB_CareerOpportunities: ['Very Important' 'Very Unimportant' 'Important' 'Neutral' 'Unimportant']
BB_HS: ['Very Important' 'Very Unimportant' 'Neutral' 'Important' 'Unimportant']
SN_Family: ['Significant Influence' 'Very little Influence' 'Extreme Influence'
 'No Influence at all' 'Moderate Influence']
SN_Friends: ['Significant Influence' 'Moderate Influence' 'Very little Influence'
 'No Influence at all' 'Extreme Influence']
SN_Seniors: ['No Influence at all' 'Very little Influence' 'Significant Influence'
 'Extreme Influence' 'Moderate Influence']
SN_RelativesNeighbors: ['No Influence at all' 'Moderate Influence' 'Significant Influence'
 'Very little Influence' 'Extreme Influence']
SN_Teachers: ['No Influence at all' 'Very little Influence' 'Extreme Influence'
 'Moderate Influence' 'Significant Influence']
SN_SameBehaviour: [4 1 3 2 5]
Selfesteem: [5 4 3 1 2]
PB_ScholarshipAvailability: ['Neutral' 'Very Unimportant' 'Important' 'Very Important' 'Unimportant']
PB_UniversityTeamGuidance: ['Important' 'Very Unimportant' 'Neutral' 'Very Important' 'Unimportant']
PB_LanguageSpoken: ['Important' 'Very Unimportant' 'Neutral' 'Very Important' 'Unimportant']
PB_AccomodationCostofLiving: ['Important' 'Very Unimportant' 'Very Important' 'Neutral' 'Unimportant']
PB_SafetyinCampus: ['Very Important' 'Very Unimportant' 'Neutral' 'Important' 'Unimportant']
PB_UniversitylocatedCity: ['Very Important' 'Very Unimportant' 'Unimportant' 'Important' 'Neutral']
PB_CourseFee: ['Very Important' 'Very Unimportant' 'Important' 'Neutral' 'Unimportant']
PB_Ranking: ['Very Important' 'Very Unimportant' 'Neutral' 'Unimportant' 'Important']
PB_ReputationBrand: ['Very Important' 'Very Unimportant' 'Neutral' 'Important' 'Unimportant']
PB_AvailabilityofCourse: ['Very Important' 'Very Unimportant' 'Neutral' 'Unimportant' 'Important']
PB_NearbytoHome: ['Important' 'Very Unimportant' 'Very Important' 'Unimportant' 'Neutral']

In [7]:
response_map = {
    'Very Unimportant': 1,
    'Unimportant': 2,
    'Neutral': 3,
    'Important': 4,
    'Very Important': 5,
    'No Influence at all': 1,
    'Very little Influence': 2,
    'Moderate Influence':3,
    'Significant Influence':4,
    'Extreme Influence':5
}

df1 = df.replace(response_map)

In [8]:
# Define the split ratio (e.g., 50% for EFA, 50% for CFA)

efa_size = 0.5  # Adjust this ratio as needed

# Perform the split

efa_data, cfa_data = train_test_split(df1, test_size=efa_size, random_state=42)

In [9]:
cfa_data.columns

Index(['BB_ToU', 'BB_AcademicReputation', 'BB_ProgramOffered',
       'BB_CourseCurriculum', 'BB_CulturalExperience',
       'BB_Facilities_resources', 'BB_SafetyCampus', 'BB_DressCode',
       'BB_Infrastructure', 'BB_FacultyProfile', 'BB_Discipline',
       'BB_CareerOpportunities', 'BB_HS', 'SN_Family', 'SN_Friends',
       'SN_Seniors', 'SN_RelativesNeighbors', 'SN_Teachers',
       'SN_SameBehaviour', 'Selfesteem', 'PB_ScholarshipAvailability',
       'PB_UniversityTeamGuidance', 'PB_LanguageSpoken',
       'PB_AccomodationCostofLiving', 'PB_SafetyinCampus',
       'PB_UniversitylocatedCity', 'PB_CourseFee', 'PB_Ranking',
       'PB_ReputationBrand', 'PB_AvailabilityofCourse', 'PB_NearbytoHome'],
      dtype='object')

In [10]:
model_desc = """
# Measurement model
Behavioural_Beliefs =~ BB_ToU + BB_AcademicReputation + BB_ProgramOffered + BB_CourseCurriculum + BB_CulturalExperience + BB_Facilities_resources + BB_SafetyCampus + BB_DressCode + BB_Infrastructure + BB_FacultyProfile + BB_Discipline + BB_CareerOpportunities + BB_HS
Normative_Beliefs =~ SN_Family + SN_Friends + SN_Seniors + SN_RelativesNeighbors + SN_Teachers + SN_SameBehaviour + Selfesteem
Perceived_Behavioural =~ PB_ScholarshipAvailability + PB_UniversityTeamGuidance + PB_LanguageSpoken + PB_AccomodationCostofLiving + PB_SafetyinCampus + PB_UniversitylocatedCity + PB_CourseFee + PB_Ranking + PB_ReputationBrand + PB_AvailabilityofCourse + PB_NearbytoHome 
"""

# Step 3: Create and fit the model
model = Model(model_desc)
model.fit(cfa_data)

# Step 4: Output the results
results = model.inspect()
print(results)

                     lval  op                   rval  Estimate  Std. Err  \
0                  BB_ToU   ~    Behavioural_Beliefs  1.000000         -
1   BB_AcademicReputation   ~    Behavioural_Beliefs  1.105514  0.042062
2       BB_ProgramOffered   ~    Behavioural_Beliefs  1.046023  0.041718
3     BB_CourseCurriculum   ~    Behavioural_Beliefs  1.118049  0.041358
4   BB_CulturalExperience   ~    Behavioural_Beliefs  1.034123  0.041976
..                    ...  ..                    ...       ...       ...
63  SN_RelativesNeighbors  ~~  SN_RelativesNeighbors  0.909209  0.074064
64       SN_SameBehaviour  ~~       SN_SameBehaviour  1.847015  0.128799
65             SN_Seniors  ~~             SN_Seniors  0.642506  0.064337
66            SN_Teachers  ~~            SN_Teachers  0.973670  0.081277
67             Selfesteem  ~~             Selfesteem  1.258256  0.087914

      z-value p-value
0           -       -
1   26.283077     0.0
2   25.073891     0.0
3   27.033514     0.0
4   24.636327     0.0
..        ...     ...
63  12.275998     0.0
64  14.340299     0.0
65    9.98655     0.0
66  11.979591     0.0
67   14.31236     0.0

[68 rows x 7 columns]

In [11]:
results.to_csv("CFA_results.csv", index=False)

In [12]:
from semopy import ModelMeans

mod = ModelMeans(model_desc)
mod.fit(df1)
mod.inspect()

,lval,op,rval,Estimate,Std. Err,z-value,p-value
0,BB_ToU,~,Behavioural_Beliefs,1.000000,-,-,-
1,BB_AcademicReputation,~,Behavioural_Beliefs,1.108257,0.029952,37.001592,0.0
2,BB_ProgramOffered,~,Behavioural_Beliefs,1.046015,0.029879,35.008201,0.0
3,BB_CourseCurriculum,~,Behavioural_Beliefs,1.131912,0.029343,38.575503,0.0
4,BB_CulturalExperience,~,Behavioural_Beliefs,1.019962,0.029592,34.467137,0.0
...,...,...,...,...,...,...,...
94,SN_RelativesNeighbors,~~,SN_RelativesNeighbors,0.836084,0.04843,17.263633,0.0
95,SN_SameBehaviour,~~,SN_SameBehaviour,1.855897,0.091543,20.273471,0.0
96,SN_Seniors,~~,SN_Seniors,0.575618,0.042157,13.654142,0.0
97,SN_Teachers,~~,SN_Teachers,0.856877,0.0524,16.352715,0.0
98,Selfesteem,~~,Selfesteem,1.187077,0.058584,20.262805,0.0

In [13]:
from semopy import ModelMeans
from semopy.stats import calc_stats

# Step 1: Fit the model
model = ModelMeans(model_desc)
model.fit(cfa_data)

# Step 2: Get parameter estimates
print(model.inspect())

                     lval  op                   rval  Estimate  Std. Err  \
0                  BB_ToU   ~    Behavioural_Beliefs  1.000000         -
1   BB_AcademicReputation   ~    Behavioural_Beliefs  1.105577  0.042072
2       BB_ProgramOffered   ~    Behavioural_Beliefs  1.046195   0.04173
3     BB_CourseCurriculum   ~    Behavioural_Beliefs  1.118158  0.041369
4   BB_CulturalExperience   ~    Behavioural_Beliefs  1.034275  0.041987
..                    ...  ..                    ...       ...       ...
94  SN_RelativesNeighbors  ~~  SN_RelativesNeighbors  0.909262  0.074068
95       SN_SameBehaviour  ~~       SN_SameBehaviour  1.846709  0.128777
96             SN_Seniors  ~~             SN_Seniors  0.642557  0.064341
97            SN_Teachers  ~~            SN_Teachers  0.973652  0.081278
98             Selfesteem  ~~             Selfesteem  1.258243  0.087913

      z-value p-value
0           -       -
1   26.278441     0.0
2   25.070863     0.0
3   27.029043     0.0
4   24.633203     0.0
..        ...     ...
94  12.276086     0.0
95  14.340305     0.0
96   9.986662     0.0
97  11.979296     0.0
98  14.312334     0.0

[99 rows x 7 columns]

In [14]:
# Step 3: Get model fit statistics
stats = calc_stats(model)
print(stats)

       DoF  DoF Baseline       chi2  chi2 p-value  chi2 Baseline       CFI  \
Value  400           434  18.404707           1.0      49.980195  0.006314

           GFI     AGFI      NFI      TLI  RMSEA        AIC         BIC  \
Value  0.63176  0.60046  0.63176 -0.07815      0  185.03928  571.522414

        LogLik
Value  3.48036

In [15]:
for key, value in stats.items():
    print(f"{key}: {value}")

DoF: Value    400
Name: DoF, dtype: int64
DoF Baseline: Value    434
Name: DoF Baseline, dtype: int64
chi2: Value    18.404707
Name: chi2, dtype: float64
chi2 p-value: Value    1.0
Name: chi2 p-value, dtype: float64
chi2 Baseline: Value    49.980195
Name: chi2 Baseline, dtype: float64
CFI: Value    0.006314
Name: CFI, dtype: float64
GFI: Value    0.63176
Name: GFI, dtype: float64
AGFI: Value    0.60046
Name: AGFI, dtype: float64
NFI: Value    0.63176
Name: NFI, dtype: float64
TLI: Value   -0.07815
Name: TLI, dtype: float64
RMSEA: Value    0
Name: RMSEA, dtype: int64
AIC: Value    185.03928
Name: AIC, dtype: float64
BIC: Value    571.522414
Name: BIC, dtype: float64
LogLik: Value    3.48036
Name: LogLik, dtype: float64

In [16]:
print("Sample size:", cfa_data.shape[0])

Sample size: 414

In [17]:
mod.inspect(std_est=True)

,lval,op,rval,Estimate,Est. Std,Std. Err,z-value,p-value
0,BB_ToU,~,Behavioural_Beliefs,1.000000,0.841185,-,-,-
1,BB_AcademicReputation,~,Behavioural_Beliefs,1.108257,0.920183,0.029952,37.001592,0.0
2,BB_ProgramOffered,~,Behavioural_Beliefs,1.046015,0.894152,0.029879,35.008201,0.0
3,BB_CourseCurriculum,~,Behavioural_Beliefs,1.131912,0.939322,0.029343,38.575503,0.0
4,BB_CulturalExperience,~,Behavioural_Beliefs,1.019962,0.886721,0.029592,34.467137,0.0
...,...,...,...,...,...,...,...,...
94,SN_RelativesNeighbors,~~,SN_RelativesNeighbors,0.836084,0.501855,0.04843,17.263633,0.0
95,SN_SameBehaviour,~~,SN_SameBehaviour,1.855897,0.976282,0.091543,20.273471,0.0
96,SN_Seniors,~~,SN_Seniors,0.575618,0.319943,0.042157,13.654142,0.0
97,SN_Teachers,~~,SN_Teachers,0.856877,0.439402,0.0524,16.352715,0.0
98,Selfesteem,~~,Selfesteem,1.187077,0.972936,0.058584,20.262805,0.0

In [18]:
model_desc = """
# Measurement model
Behavioural_Beliefs =~ BB_ToU + BB_AcademicReputation + BB_ProgramOffered + BB_CourseCurriculum + BB_CulturalExperience + BB_Facilities_resources + BB_SafetyCampus + BB_DressCode + BB_Infrastructure + BB_FacultyProfile + BB_Discipline + BB_CareerOpportunities + BB_HS
Normative_Beliefs =~ SN_Family + SN_Friends + SN_Seniors + SN_RelativesNeighbors + SN_Teachers
Perceived_Behavioural =~ PB_ScholarshipAvailability + PB_UniversityTeamGuidance + PB_LanguageSpoken + PB_AccomodationCostofLiving + PB_SafetyinCampus + PB_UniversitylocatedCity + PB_CourseFee + PB_Ranking + PB_ReputationBrand + PB_AvailabilityofCourse + PB_NearbytoHome 
"""

# Step 3: Create and fit the model
model = Model(model_desc)
model.fit(cfa_data)

# Step 4: Output the results
results = model.inspect()
print(results)

                     lval  op                   rval  Estimate  Std. Err  \
0                  BB_ToU   ~    Behavioural_Beliefs  1.000000         -
1   BB_AcademicReputation   ~    Behavioural_Beliefs  1.105503  0.042067
2       BB_ProgramOffered   ~    Behavioural_Beliefs  1.046120  0.041725
3     BB_CourseCurriculum   ~    Behavioural_Beliefs  1.118077  0.041364
4   BB_CulturalExperience   ~    Behavioural_Beliefs  1.034202  0.041983
..                    ...  ..                    ...       ...       ...
59              SN_Family  ~~              SN_Family  1.283226  0.098193
60             SN_Friends  ~~             SN_Friends  0.579247  0.058677
61  SN_RelativesNeighbors  ~~  SN_RelativesNeighbors  0.904881  0.073948
62             SN_Seniors  ~~             SN_Seniors  0.649896  0.064825
63            SN_Teachers  ~~            SN_Teachers  0.976542  0.081547

      z-value p-value
0           -       -
1   26.279463     0.0
2   25.071672     0.0
3   27.029944     0.0
4   24.633924     0.0
..        ...     ...
59   13.06841     0.0
60   9.871749     0.0
61  12.236768     0.0
62  10.025444     0.0
63  11.975158     0.0

[64 rows x 7 columns]

In [19]:
results_std = model.inspect(std_est=True)
print(results_std)

                     lval  op                   rval  Estimate  Est. Std  \
0                  BB_ToU   ~    Behavioural_Beliefs  1.000000  0.842504
1   BB_AcademicReputation   ~    Behavioural_Beliefs  1.105503  0.920361
2       BB_ProgramOffered   ~    Behavioural_Beliefs  1.046120  0.898451
3     BB_CourseCurriculum   ~    Behavioural_Beliefs  1.118077  0.933239
4   BB_CulturalExperience   ~    Behavioural_Beliefs  1.034202  0.890131
..                    ...  ..                    ...       ...       ...
59              SN_Family  ~~              SN_Family  1.283226  0.646652
60             SN_Friends  ~~             SN_Friends  0.579247  0.355129
61  SN_RelativesNeighbors  ~~  SN_RelativesNeighbors  0.904881  0.531524
62             SN_Seniors  ~~             SN_Seniors  0.649896  0.363288
63            SN_Teachers  ~~            SN_Teachers  0.976542  0.503707

    Std. Err    z-value p-value
0          -          -       -
1   0.042067  26.279463     0.0
2   0.041725  25.071672     0.0
3   0.041364  27.029944     0.0
4   0.041983  24.633924     0.0
..       ...        ...     ...
59  0.098193   13.06841     0.0
60  0.058677   9.871749     0.0
61  0.073948  12.236768     0.0
62  0.064825  10.025444     0.0
63  0.081547  11.975158     0.0

[64 rows x 8 columns]

In [20]:
mod.inspect(std_est=True)

,lval,op,rval,Estimate,Est. Std,Std. Err,z-value,p-value
0,BB_ToU,~,Behavioural_Beliefs,1.000000,0.841185,-,-,-
1,BB_AcademicReputation,~,Behavioural_Beliefs,1.108257,0.920183,0.029952,37.001592,0.0
2,BB_ProgramOffered,~,Behavioural_Beliefs,1.046015,0.894152,0.029879,35.008201,0.0
3,BB_CourseCurriculum,~,Behavioural_Beliefs,1.131912,0.939322,0.029343,38.575503,0.0
4,BB_CulturalExperience,~,Behavioural_Beliefs,1.019962,0.886721,0.029592,34.467137,0.0
...,...,...,...,...,...,...,...,...
94,SN_RelativesNeighbors,~~,SN_RelativesNeighbors,0.836084,0.501855,0.04843,17.263633,0.0
95,SN_SameBehaviour,~~,SN_SameBehaviour,1.855897,0.976282,0.091543,20.273471,0.0
96,SN_Seniors,~~,SN_Seniors,0.575618,0.319943,0.042157,13.654142,0.0
97,SN_Teachers,~~,SN_Teachers,0.856877,0.439402,0.0524,16.352715,0.0
98,Selfesteem,~~,Selfesteem,1.187077,0.972936,0.058584,20.262805,0.0

In [18]:
# Step 3: Get model fit statistics
stats = calc_stats(model)
print(stats)

       DoF  DoF Baseline         chi2  chi2 p-value  chi2 Baseline      CFI  \
Value  374           406  1343.973426           0.0   14398.785478  0.93068

            GFI      AGFI       NFI       TLI     RMSEA         AIC  \
Value  0.906661  0.898674  0.906661  0.924749  0.079244  115.507375

              BIC    LogLik
Value  361.085199  3.246313

In [24]:
import pandas as pd

# Filter relevant rows
loadings = results.query('op == "~"')[['lhs', 'rhs', 'est']]
errors = results.query('op == "~~" and lhs == rhs')[['lhs', 'est']]

# Compute CR and AVE
latent_vars = loadings['lhs'].unique()
validity = []

for lv in latent_vars:
    lv_loadings = loadings[loadings['lhs'] == lv]['est'].values
    lv_items = loadings[loadings['lhs'] == lv]['rhs'].values
    lv_errors = errors[errors['lhs'].isin(lv_items)]['est'].values

    CR = (sum(lv_loadings))**2 / ((sum(lv_loadings))**2 + sum(lv_errors))
    AVE = sum(lv_loadings**2) / len(lv_loadings)

    validity.append({'Latent Variable': lv, 'CR': round(CR, 3), 'AVE': round(AVE, 3)})

cr_ave_df = pd.DataFrame(validity)
print("🔍 Convergent Validity:")
print(cr_ave_df)

KeyError: "None of [Index(['lhs', 'rhs', 'est'], dtype='object')] are in the [columns]"

In [25]:
print(results.columns)

Index(['lval', 'op', 'rval', 'Estimate', 'Std. Err', 'z-value', 'p-value'], dtype='object')

In [26]:
print(type(results))

<class 'pandas.core.frame.DataFrame'>

In [27]:
import pandas as pd

# Filter loadings and error variances using updated column names
loadings = results.query('op == "~"')[['lval', 'rval', 'Estimate']]
errors = results.query('op == "~~" and lval == rval')[['lval', 'Estimate']]

# Compute CR and AVE
latent_vars = loadings['lval'].unique()
validity = []

for lv in latent_vars:
    lv_loadings = loadings[loadings['lval'] == lv]['Estimate'].values
    lv_items = loadings[loadings['lval'] == lv]['rval'].values
    lv_errors = errors[errors['lval'].isin(lv_items)]['Estimate'].values

    CR = (sum(lv_loadings))**2 / ((sum(lv_loadings))**2 + sum(lv_errors))
    AVE = sum(lv_loadings**2) / len(lv_loadings)

    validity.append({'Latent Variable': lv, 'CR': round(CR, 3), 'AVE': round(AVE, 3)})

cr_ave_df = pd.DataFrame(validity)
print("🔍 Convergent Validity:")
print(cr_ave_df)

🔍 Convergent Validity:
                Latent Variable     CR    AVE
0                        BB_ToU  0.419  1.000
1         BB_AcademicReputation  0.469  1.222
2             BB_ProgramOffered  0.442  1.094
3           BB_CourseCurriculum  0.475  1.250
4         BB_CulturalExperience  0.436  1.070
5       BB_Facilities_resources  0.472  1.239
6               BB_SafetyCampus  0.482  1.288
7                  BB_DressCode  0.254  0.471
8             BB_Infrastructure  0.414  0.977
9             BB_FacultyProfile  0.454  1.153
10                BB_Discipline  0.447  1.118
11       BB_CareerOpportunities  0.495  1.356
12                        BB_HS  0.470  1.230
13                    SN_Family  0.588  1.000
14                   SN_Friends  0.681  1.500
15                   SN_Seniors  0.698  1.624
16        SN_RelativesNeighbors  0.619  1.137
17                  SN_Teachers  0.662  1.372
18   PB_ScholarshipAvailability  0.555  1.000
19    PB_UniversityTeamGuidance  0.654  1.520
20            PB_LanguageSpoken  0.626  1.342
21  PB_AccomodationCostofLiving  0.670  1.627
22            PB_SafetyinCampus  0.707  1.933
23     PB_UniversitylocatedCity  0.662  1.574
24                 PB_CourseFee  0.674  1.663
25                   PB_Ranking  0.713  1.994
26           PB_ReputationBrand  0.700  1.877
27      PB_AvailabilityofCourse  0.708  1.948
28              PB_NearbytoHome  0.539  0.938

In [28]:
import pandas as pd

# Filter for loadings and error variances
loadings = results.query('op == "~"')[['lval', 'rval', 'Estimate']]
errors = results.query('op == "~~" and lval == rval')[['lval', 'Estimate']]

# Map latent variables to their items
latent_map = loadings.groupby('lval')['rval'].apply(list).to_dict()
validity = []

for lv, items in latent_map.items():
    lv_loadings = loadings[loadings['lval'] == lv]['Estimate'].values
    lv_errors = errors[errors['lval'].isin(items)]['Estimate'].values

    CR = (sum(lv_loadings))**2 / ((sum(lv_loadings))**2 + sum(lv_errors))
    AVE = sum(lv_loadings**2) / len(lv_loadings)

    validity.append({'Latent Variable': lv, 'CR': round(CR, 3), 'AVE': round(AVE, 3)})

cr_ave_df = pd.DataFrame(validity)
print("🔍 Corrected Convergent Validity:")
print(cr_ave_df)

🔍 Corrected Convergent Validity:
                Latent Variable     CR    AVE
0         BB_AcademicReputation  0.469  1.222
1        BB_CareerOpportunities  0.495  1.356
2           BB_CourseCurriculum  0.475  1.250
3         BB_CulturalExperience  0.436  1.070
4                 BB_Discipline  0.447  1.118
5                  BB_DressCode  0.254  0.471
6       BB_Facilities_resources  0.472  1.239
7             BB_FacultyProfile  0.454  1.153
8                         BB_HS  0.470  1.230
9             BB_Infrastructure  0.414  0.977
10            BB_ProgramOffered  0.442  1.094
11              BB_SafetyCampus  0.482  1.288
12                       BB_ToU  0.419  1.000
13  PB_AccomodationCostofLiving  0.670  1.627
14      PB_AvailabilityofCourse  0.708  1.948
15                 PB_CourseFee  0.674  1.663
16            PB_LanguageSpoken  0.626  1.342
17              PB_NearbytoHome  0.539  0.938
18                   PB_Ranking  0.713  1.994
19           PB_ReputationBrand  0.700  1.877
20            PB_SafetyinCampus  0.707  1.933
21   PB_ScholarshipAvailability  0.555  1.000
22    PB_UniversityTeamGuidance  0.654  1.520
23     PB_UniversitylocatedCity  0.662  1.574
24                    SN_Family  0.588  1.000
25                   SN_Friends  0.681  1.500
26        SN_RelativesNeighbors  0.619  1.137
27                   SN_Seniors  0.698  1.624
28                  SN_Teachers  0.662  1.372

In [37]:
import pandas as pd
import numpy as np

# Example: Use your actual output from semopy
inspect_df = mod.inspect(std_est=True)

# Filter rows where 'op' indicates factor loadings (i.e., latent to observed paths)
loadings_df = inspect_df[inspect_df['op'] == '~']

# Create a dictionary mapping latent constructs to their observed variables
construct_items = {}
for _, row in loadings_df.iterrows():
    indicator = row['lval']
    latent = row['rval']
    if latent not in construct_items:
        construct_items[latent] = []
    construct_items[latent].append(indicator)

In [38]:
# Merge the constructs and their standardized loadings
ave_dict = {}

for construct, items in construct_items.items():
    squared_loadings = loadings_df[
        (loadings_df['rval'] == construct) &
        (loadings_df['lval'].isin(items))
    ]['Est. Std'].astype(float) ** 2
    
    ave = squared_loadings.mean()
    ave_dict[construct] = ave

constructs = list(construct_items.keys())
fl_matrix = pd.DataFrame(index=constructs, columns=constructs)

# Fill Fornell-Larcker matrix
for c1 in constructs:
    for c2 in constructs:
        if c1 == c2:
            fl_matrix.loc[c1, c2] = round(np.sqrt(ave_dict[c1]), 3)
        else:
            # For between-construct correlations, extract from your latent variable correlation matrix
            # If not available, placeholder: assume 0.5
            fl_matrix.loc[c1, c2] = "Need latent correlation matrix"

print("📊 Fornell-Larcker Matrix:")
print(fl_matrix)

📊 Fornell-Larcker Matrix:
                                  Behavioural_Beliefs  \
Behavioural_Beliefs                             0.888
Normative_Beliefs      Need latent correlation matrix
Perceived_Behavioural  Need latent correlation matrix
1                      Need latent correlation matrix

                                    Normative_Beliefs  \
Behavioural_Beliefs    Need latent correlation matrix
Normative_Beliefs                               0.629
Perceived_Behavioural  Need latent correlation matrix
1                      Need latent correlation matrix

                                Perceived_Behavioural  \
Behavioural_Beliefs    Need latent correlation matrix
Normative_Beliefs      Need latent correlation matrix
Perceived_Behavioural                           0.848
1                      Need latent correlation matrix

                                                    1
Behavioural_Beliefs    Need latent correlation matrix
Normative_Beliefs      Need latent correlation matrix
Perceived_Behavioural  Need latent correlation matrix
1                                               2.602

In [39]:
def compute_htmt(data, construct_items):
    constructs = list(construct_items.keys())
    htmt_matrix = pd.DataFrame(index=constructs, columns=constructs)

    for c1 in constructs:
        for c2 in constructs:
            if c1 == c2:
                htmt_matrix.loc[c1, c2] = 1.0
            else:
                items1 = construct_items[c1]
                items2 = construct_items[c2]
                cor_matrix = data[items1 + items2].corr()
                het_trait = cor_matrix.loc[items1, items2].abs().values.flatten()
                mono_trait1 = cor_matrix.loc[items1, items1].where(np.triu(np.ones((len(items1), len(items1)), 1)).astype(bool)).stack().abs().values
                mono_trait2 = cor_matrix.loc[items2, items2].where(np.triu(np.ones((len(items2), len(items2)), 1)).astype(bool)).stack().abs().values

                denominator = np.mean(np.concatenate([mono_trait1, mono_trait2]))
                htmt = np.mean(het_trait) / denominator if denominator != 0 else 0
                htmt_matrix.loc[c1, c2] = round(htmt, 3)
    return htmt_matrix

# Example: assuming your raw data used for CFA is 'cfa_data'
htmt_result = compute_htmt(cfa_data, construct_items)

print("\n📊 HTMT Matrix:")
print(htmt_result)

TypeError: Cannot interpret '1' as a data type

In [42]:
def compute_htmt(data, construct_items):
    constructs = list(construct_items.keys())
    htmt_matrix = pd.DataFrame(index=constructs, columns=constructs)

    for c1 in constructs:
        for c2 in constructs:
            if c1 == c2:
                htmt_matrix.loc[c1, c2] = 1.0
            else:
                items1 = construct_items[c1]
                items2 = construct_items[c2]
                cor_matrix = data[items1 + items2].corr()

                # Heterotrait-Monotrait correlations
                het_trait = cor_matrix.loc[items1, items2].abs().values.flatten()

                # Mono-trait for construct 1
                mt1 = cor_matrix.loc[items1, items1]
                mask1 = np.triu(np.ones(mt1.shape), k=1).astype(bool)
                mask1_df = pd.DataFrame(mask1, index=mt1.index, columns=mt1.columns)
                mono_trait1 = mt1.where(mask1_df).stack().abs().values

                # Mono-trait for construct 2
                mt2 = cor_matrix.loc[items2, items2]
                mask2 = np.triu(np.ones(mt2.shape), k=1).astype(bool)
                mask2_df = pd.DataFrame(mask2, index=mt2.index, columns=mt2.columns)
                mono_trait2 = mt2.where(mask2_df).stack().abs().values

                # Combine and compute HTMT
                denominator = np.mean(np.concatenate([mono_trait1, mono_trait2]))
                htmt_val = np.mean(het_trait) / denominator if denominator != 0 else 0
                htmt_matrix.loc[c1, c2] = round(htmt_val, 3)

    return htmt_matrix

In [43]:
htmt_result = compute_htmt(cfa_data, construct_items)
print("\n📊 HTMT Matrix:")
print(htmt_result)

📊 HTMT Matrix:
                      Behavioural_Beliefs Normative_Beliefs  \
Behavioural_Beliefs                   1.0             0.205
Normative_Beliefs                   0.205               1.0
Perceived_Behavioural               0.658             0.292
1                                   1.063             0.681

                      Perceived_Behavioural      1
Behavioural_Beliefs                   0.658  1.063
Normative_Beliefs                     0.292  0.681
Perceived_Behavioural                   1.0  1.062
1                                     1.062    1.0

In [19]:
for key, value in stats.items():
    print(f"{key}: {value}")

DoF: Value    374
Name: DoF, dtype: int64
DoF Baseline: Value    406
Name: DoF Baseline, dtype: int64
chi2: Value    1343.973426
Name: chi2, dtype: float64
chi2 p-value: Value    0.0
Name: chi2 p-value, dtype: float64
chi2 Baseline: Value    14398.785478
Name: chi2 Baseline, dtype: float64
CFI: Value    0.93068
Name: CFI, dtype: float64
GFI: Value    0.906661
Name: GFI, dtype: float64
AGFI: Value    0.898674
Name: AGFI, dtype: float64
NFI: Value    0.906661
Name: NFI, dtype: float64
TLI: Value    0.924749
Name: TLI, dtype: float64
RMSEA: Value    0.079244
Name: RMSEA, dtype: float64
AIC: Value    115.507375
Name: AIC, dtype: float64
BIC: Value    361.085199
Name: BIC, dtype: float64
LogLik: Value    3.246313
Name: LogLik, dtype: float64

In [28]:

# ✅ Step 3: Fit the model
model = Model(model_desc)
model.fit(cfa_data)

# ✅ Step 4: Generate horizontal path diagram
graph = semplot(model, plot=False)
graph.graph_attr['rankdir'] = 'LR'  # Horizontal layout

# ✅ Step 5: Save the image
graph.render("cfa_horizontal", format="png", cleanup=True)

print("✅ Horizontal CFA diagram saved as 'cfa_horizontal.png'")

TypeError: semplot() got an unexpected keyword argument 'plot'

In [30]:
# ✅ Fit the model
model = Model(model_desc)
model.fit(cfa_data)

# ✅ Create and save the path diagram (top-down layout only)
semplot(model, "cfa_diagram_topdown.png")

print("✅ CFA diagram saved as 'cfa_diagram_topdown.png'")

✅ CFA diagram saved as 'cfa_diagram_topdown.png'

In [3]:
python --version

NameError: name 'python' is not defined